"""Adding models

Revision ID: 0ed0f79f52df
Revises:
Create Date: 2025-02-12 22:51:42.891344

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "0ed0f79f52df"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
