"""Adding models

Revision ID: 6001efd83292
Revises: 0ed0f79f52df
Create Date: 2025-02-12 22:53:12.298527

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "6001efd83292"
down_revision: Union[str, None] = "0ed0f79f52df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
